### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by bvelazquez1** [apexad/homebridge-mysmartrollershades-bridge#4]
Hello! 
I am not a coder or dev. I am a full noob. I attempted to install this plugin into my homebridge and it doesn't to install anything. I open up my terminal and attempted to install using "npm install" but it returns this error: 

npm ERR! code ENOVERSIONS
npm ERR! No versions available for homebridge-mysmartrollershades-bridge

I have homebridge running on a Raspberry Pi. I currently have v1.3.9 of homebridge. My node.js version is v16.13.0 and my npm version is v8.1.2.

**Comment by apexad** [comment]
This plugin is still a work in progress. Lot’s of research has been done and I hope to get this working soon, but don’t have an ETA.
